"""Stage 3 — timeline JSON to .jsfl command files (PRD sections 8, 9, 11).

Output is one or more .jsfl files, each carrying the runtime plus a batch of
ops. Batching is not cosmetic: JSFL runs synchronously on Animate's main thread,
so a single file with hundreds of lines makes Animate look hung (PRD 9).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import actions
import map_frames

RUNTIME_PATH = Path(__file__).resolve().parent / "jsfl_runtime.jsfl"


def build_ops(timeline: dict) -> list[dict]:
    """Lower every line of the timeline JSON into runtime primitives."""
    ctx = actions.context_from_config(timeline.get("config", {"fps": timeline["fps"]}))
    ops: list[dict] = []
    for line, entry in map_frames.lines_from_timeline(timeline):
        layers = [subject["layer"] for subject in entry["subjects"]]
        ops += actions.emit_line(ctx, line, layers, entry["start_frame"], entry["end_frame"])
    return ops


def chunk(ops: list[dict], batch_size: int) -> list[list[dict]]:
    """Split on line boundaries so a batch never cuts a line in half."""
    if batch_size <= 0:
        return [ops]
    batches: list[list[dict]] = []
    current: list[dict] = []
    lines_in_batch = 0
    for op in ops:
        if op["op"] == "comment" and current and lines_in_batch >= batch_size:
            batches.append(current)
            current, lines_in_batch = [], 0
        if op["op"] == "comment":
            lines_in_batch += 1
        current.append(op)
    if current:
        batches.append(current)
    return batches


def audio_uri(timeline: dict, audio_path: str | None) -> str:
    """JSFL wants a file:/// URI, not a filesystem path."""
    path = audio_path or timeline.get("audio_file", "")
    if not path:
        return ""
    return Path(path).resolve().as_uri()


def render(timeline: dict, ops: list[dict], batch: int, batches: int, uri: str, save: bool) -> str:
    config = timeline.get("config", {})
    audio_layer = config.get("audio_layer", {})
    options = {
        "fps": timeline["fps"],
        "batch": batch,
        "batches": batches,
        "save": save,
        # Only the first batch imports the voice-over.
        "audio_uri": uri if batch == 1 else "",
        "audio_layer": audio_layer.get("name", "VO"),
        "audio_position": audio_layer.get("position", "bottom"),
    }
    return "\n".join(
        [
            f"// Generated by voice-anim-agent — batch {batch} of {batches}. Do not edit by hand;",
            "// regenerate from timeline.json instead (that JSON is the source of truth).",
            "",
            RUNTIME_PATH.read_text(encoding="utf-8").rstrip(),
            "",
            f"VAA.run({json.dumps(options, ensure_ascii=False)}, {json.dumps(ops, ensure_ascii=False, indent=2)});",
            "",
        ]
    )


def write_batches(
    timeline: dict,
    out_dir: str | Path,
    stem: str = "vaa",
    audio_path: str | None = None,
) -> list[Path]:
    config = timeline.get("config", {})
    ops = build_ops(timeline)
    batches = chunk(ops, int(config.get("batch_size", 50)))
    save = bool(config.get("auto_save_each_batch", True))
    uri = audio_uri(timeline, audio_path)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for index, batch_ops in enumerate(batches, start=1):
        path = out_dir / (f"{stem}.jsfl" if len(batches) == 1 else f"{stem}_batch{index:02d}.jsfl")
        path.write_text(
            render(timeline, batch_ops, index, len(batches), uri, save), encoding="utf-8"
        )
        written.append(path)
    return written


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate .jsfl from a timeline JSON.")
    parser.add_argument("--timeline", required=True, help="timeline.json from map_frames.py")
    parser.add_argument("--out-dir", default="out", help="where to write the .jsfl files")
    parser.add_argument("--stem", default="vaa", help="output filename stem")
    parser.add_argument("--audio", help="voice-over path to import (overrides the JSON)")
    args = parser.parse_args(argv)

    timeline = json.loads(Path(args.timeline).read_text(encoding="utf-8"))
    written = write_batches(timeline, args.out_dir, args.stem, args.audio)
    for path in written:
        print(f"wrote {path}")
    print(
        "run these in Animate with Commands > Run Command, in order "
        "(the Master Library .fla must be the active document)"
    )
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    raise SystemExit(main())
